[general]
destination = "$HOME/.config/hypr/monitors.conf"

[power_events]
[power_events.dbus_query_object]
path = "/org/freedesktop/UPower/devices/line_power_ACAD"

[[power_events.dbus_signal_match_rules]]
object_path = "/org/freedesktop/UPower/devices/line_power_ACAD"

[static_template_values]
default_vrr = "1"
default_scale = "2.0"
default_res = "2880x1800"
refresh_rate_high = "120.00000"
refresh_rate_low = "60.00000"

# Docked AC
[profiles.docked_ac]
config_file = "hyprconfigs/docked_ac.go.tmpl"
config_file_type = "template"

# [profiles.docked_ac.conditions]
# power_state = "AC"

[[profiles.docked_ac.conditions.required_monitors]]
description = "ATNA40CU05-0"
match_description_using_regex = true
monitor_tag = "laptop"

[[profiles.docked_ac.conditions.required_monitors]]
description = "LG HDR 5K 202NTQDFP636"
match_description_using_regex = true
monitor_tag = "external"

# Gaming
[profiles.gaming]
config_file = "hyprconfigs/gaming.go.tmpl"
config_file_type = "template"

[profiles.gaming.conditions]
power_state = "AC"

[[profiles.gaming.conditions.required_monitors]]
description = "ATNA40CU05-0"
match_description_using_regex = true
monitor_tag = "laptop"

[[profiles.gaming.conditions.required_monitors]]
description = "XG27AQ"
match_description_using_regex = true
monitor_tag = "external"

# Fallback
[fallback_profile]
config_file = "hyprconfigs/fallback.conf"
config_file_type = "static"
